
version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    environment:
      CLUSTER_ID: "b1pY9HpsT5q8OZqQfCKJFA==" # optional if formatted manually
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - CLICKHOUSE_USER=grafana_user
      - CLICKHOUSE_PASSWORD=grafana_pass
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - clickhouse
    volumes:
      - ./grafana:/var/lib/grafana

  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.1.8-debug
    container_name: fluent-bit
    depends_on:
      - kafka
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - logs-data:/app/logs

  log-emitter:
    build: ./spring-boot-log-emitter
    container_name: log-emitter
    ports:
      - "8081:8080"
    volumes:
      - logs-data:/app/logs

#  debug:
#    image: busybox
#    command: sh
#    stdin_open: true
#    tty: true
#    networks:
#      - default

volumes:
  logs-data:
